





































            Directory.CreateDirectory(screenshotsDirectory);            string screenshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "CSimple", "Resources", "Screenshots");        {        private void CaptureAllScreens(CancellationToken cancellationToken)        }            }                _userVisualCancellationTokenSource?.Cancel();                debugOutput($"User Visual Output: {buttonText}");                buttonText = "Read";            {            else            }                Task.Run(() => CaptureAllScreens(cancellationToken), cancellationToken);                var cancellationToken = _userVisualCancellationTokenSource.Token;                _userVisualCancellationTokenSource = new CancellationTokenSource();                debugOutput($"User Visual Output: {buttonText}");                buttonText = "Stop";            {            if (buttonText == "Read")        {        public void ToggleUserVisualOutput(ref string buttonText, Action<string> debugOutput)        private CancellationTokenSource _userVisualCancellationTokenSource;    {    public class ScreenCaptureService{namespace CSimple.Servicesusing System.Windows.Forms;using System.Threading;using System.IO;using System.Drawing.Imaging;using System.Drawing;using System.Diagnostics;